def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
]

pipeline {
    agent any

    environment {
        cluster = "vproprod"
        service = "vproappprodsvc"
    }

    stages {
        stage('Deploy to prod ECS ') {
            steps {
                withAWS(credentials: 'awscreds', region: 'us-west-1' ) {
                    sh "aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment"
                }
            }
        }            
    }
    post {
        always {
            echo 'Slack Notifications'
            slackSend channel: '#jenkinsci',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n more info at: ${env.BUILD_URL}"
        }
    }
}